-- V1：tasks テーブルを作る（Flyway を入れる前に Hibernate が自動で作っていた形を、そのまま SQL にしたもの）
-- Flyway は、このフォルダ（db/migration）の V番号__説明.sql を、番号の小さい順に1回ずつ DB へ当てる
-- 一度当てたファイルは書き換えない。テーブルを変えるときは、V2__〜.sql のように新しいファイルを足す

CREATE TABLE tasks (
    -- タスクの番号。行を足すたびに DB が自動で振る
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- タスク名（255 文字まで）
    text       VARCHAR(255) NOT NULL,
    -- 状態（todo・doing・done のどれか。決まった値かどうかはアプリ側で確かめる）
    status     VARCHAR(255) NOT NULL,
    -- 優先度（high・medium・low のどれか）
    priority   VARCHAR(255) NOT NULL,
    -- 期限日（なくてもよい）
    due_date   DATE,
    -- 同じ列の中での並び順（小さいほど上）
    sort_order INTEGER      NOT NULL
);

-- 一覧を「列ごと・並び順どおり」に取り出すときと、列の一番下（並び順の最大値）を探すときを速くする
CREATE INDEX idx_tasks_status_sort_order ON tasks (status, sort_order);
