-- V3：列を自由に追加・削除できるようにする（要件定義書 5.2 No.13）
-- 今までは、列が todo・doing・done の3つに決まっていて、タスクの status に列の名前を直接書いていた
-- これからは、列を board_columns テーブルに入れて、タスクには「どの列にいるか」を列の番号（column_id）で書く
-- （columns という名前は SQL で使われる言葉と紛らわしいので、board_columns にする）

CREATE TABLE board_columns (
    -- 列の番号。行を足すたびに DB が自動で振る
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 列の名前（255 文字まで）
    name       VARCHAR(255)     NOT NULL,
    -- 列の並び順（小さいほど左）
    sort_order DOUBLE PRECISION NOT NULL,
    -- 「完了の列」の印。完了ボタン（○）を押したタスクは、この印がついた列へ移る
    is_done    BOOLEAN          NOT NULL DEFAULT FALSE
);

-- 「完了の列」の印は、全部の列の中で1つまで
-- （is_done が TRUE の行だけを見て、同じ値が2つあれば止める）
CREATE UNIQUE INDEX uq_board_columns_one_done ON board_columns (is_done) WHERE is_done;

-- 今までの3つの列を、そのまま入れる
INSERT INTO board_columns (name, sort_order, is_done) VALUES
    ('やるべきこと', 0, FALSE),
    ('進行中',       1, FALSE),
    ('終わったこと', 2, TRUE);

-- タスクに列の番号を足して、今の status から、対応する列の番号を書き込む
ALTER TABLE tasks ADD COLUMN column_id BIGINT;

UPDATE tasks t
SET column_id = c.id
FROM board_columns c
WHERE c.name = CASE t.status
    WHEN 'todo'  THEN 'やるべきこと'
    WHEN 'doing' THEN '進行中'
    WHEN 'done'  THEN '終わったこと'
END;

-- 全部のタスクに番号が入ったので、空にできないようにする
ALTER TABLE tasks ALTER COLUMN column_id SET NOT NULL;

-- 外部キー：column_id には、board_columns にある番号しか書けない
-- また、タスクが残っている列は消せない（消そうとすると DB が止める）
ALTER TABLE tasks
    ADD CONSTRAINT fk_tasks_column FOREIGN KEY (column_id) REFERENCES board_columns (id);

-- もう使わない status と、そのインデックスを消して、列の番号で同じインデックスを作り直す
DROP INDEX idx_tasks_status_sort_order;
ALTER TABLE tasks DROP COLUMN status;
CREATE INDEX idx_tasks_column_id_sort_order ON tasks (column_id, sort_order);
